"""empty message

Revision ID: 0294025b8af9
Revises: 4df74173b793
Create Date: 2016-11-07 06:37:52.946560

"""

# revision identifiers, used by Alembic.
revision = '0294025b8af9'
down_revision = '4df74173b793'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gametable', sa.Column('description', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gametable', 'description')
    ### end Alembic commands ###
