"""empty message

Revision ID: 2fb41063ea8d
Revises: 4ed2a89201c2
Create Date: 2016-10-24 05:49:25.221863

"""

# revision identifiers, used by Alembic.
revision = '2fb41063ea8d'
down_revision = '4ed2a89201c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gametable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('table', 'author', name='_author_table')
    )
    op.create_table('gamedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_pk', sa.Integer(), nullable=True),
    sa.Column('base', sa.String(), nullable=True),
    sa.Column('combination', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_pk'], ['gametable.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'combination', name='_base_combination'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_table('gamedata')
    op.drop_table('gametable')
    ### end Alembic commands ###
