"""empty message

Revision ID: 4df74173b793
Revises: d654130ad5fe
Create Date: 2016-10-29 16:17:50.942895

"""

# revision identifiers, used by Alembic.
revision = '4df74173b793'
down_revision = 'd654130ad5fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gamedata', ['id'])
    op.create_unique_constraint(None, 'gametable', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'gametable', type_='unique')
    op.drop_constraint(None, 'gamedata', type_='unique')
    ### end Alembic commands ###
