"""empty message

Revision ID: 75568448458a
Revises: 68a660a65ac6
Create Date: 2016-08-06 16:51:29.211381

"""

# revision identifiers, used by Alembic.
revision = '75568448458a'
down_revision = '68a660a65ac6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    ### end Alembic commands ###
