"""empty message

Revision ID: cc508f369a24
Revises: e90ee08a3654
Create Date: 2016-08-06 17:27:11.247020

"""

# revision identifiers, used by Alembic.
revision = 'cc508f369a24'
down_revision = 'e90ee08a3654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
