"""empty message

Revision ID: e90ee08a3654
Revises: 75568448458a
Create Date: 2016-08-06 16:52:03.163172

"""

# revision identifiers, used by Alembic.
revision = 'e90ee08a3654'
down_revision = '75568448458a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    ### end Alembic commands ###
