"""empty message

Revision ID: f50cede16d4d
Revises: 2fb41063ea8d
Create Date: 2016-10-24 06:27:10.499270

"""

# revision identifiers, used by Alembic.
revision = 'f50cede16d4d'
down_revision = '2fb41063ea8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gametables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('table', 'author', name='_author_table')
    )
    op.drop_table('gametable')
    op.create_unique_constraint(None, 'gamedata', ['id'])
    op.drop_constraint('gamedata_table_pk_fkey', 'gamedata', type_='foreignkey')
    op.create_foreign_key(None, 'gamedata', 'gametables', ['table_pk'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamedata', type_='foreignkey')
    op.create_foreign_key('gamedata_table_pk_fkey', 'gamedata', 'gametable', ['table_pk'], ['id'])
    op.drop_constraint(None, 'gamedata', type_='unique')
    op.create_table('gametable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gametable_pkey'),
    sa.UniqueConstraint('table', 'author', name='_author_table')
    )
    op.drop_table('gametables')
    ### end Alembic commands ###
